### PR TITLE
Add new message types support, fix loading and UX improvement

### PR DESCRIPTION
**Pull request by ammarfaizi2**
This pull request contains commits for adding new message types, fix
loading handler and UX improvement. I added 3 new support message types
(photo, sticker and video).

Current supported message types are:
  1) text
  2) photo
  3) sticker
  4) video

### CODE REVIEW

**Comment by ammarfaizi2** [comment]
@Sprtcrnbry can you review?

**Comment by Sprtcrnbry** [comment]
> @Sprtcrnbry can you review?

yes, do i need anything backend to test it out?
also, sorry for the late review

**Comment by ammarfaizi2** [comment]
On Sun, Aug 8, 2021 at 1:07 PM Sprite ***@***.***> wrote:
>
> @Sprtcrnbry can you review?
>
> yes, do i need anything backend to test it out?
> also, sorry for the late review

I have added the setup instructions in commit
3043201874e8adc68296a23f7d45875b5c79e49c
("telegram/index: Add external online API support")

The commit message explains the steps. This way you don't have to do
full complicated backend setup.

**Comment by ammarfaizi2** [comment]
SHA256:6Mh/LC3SYUdfDWVoj6+h66p7kJS5OUacio91LKJ+DMU ***@***.***

On Sun, Aug 8, 2021 at 1:59 PM Ammar Faizi ***@***.***> wrote:
>
> On Sun, Aug 8, 2021 at 1:07 PM Sprite ***@***.***> wrote:
> >
> > @Sprtcrnbry can you review?
> >
> > yes, do i need anything backend to test it out?
> > also, sorry for the late review
>
> I have added the setup instructions in commit
> 3043201874e8adc68296a23f7d45875b5c79e49c ("telegram/index: Add
> external online API support")
>
> The commit message explains the steps. This way you don't have to do
> full complicated backend setup.

There was a mistake in the instruction, https should be http. It has
been reworded.

**Review by Sprtcrnbry — DISMISSED** [review]

**Review by Sprtcrnbry — APPROVED** [review]

**Review by ammarfaizi2 — COMMENTED** [review]
Alright, let's merge this.

**Pull request merged**
